packages:
  - packages/*
allowBuilds:
  "@nestjs/core": true
  "@swc/core": true
  core-js: true
  esbuild: true
  nx: true

catalog:
  "@napi-rs/cli": 3.7.2
  vite-plus: 0.2.4

verifyDepsBeforeRun: install

minimumReleaseAgeExclude:
  - "@oxc-project/*"
